version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-presigned-url"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1cdwopih9y0ls"
s3_prefix = "sam-presigned-url"
region = "ap-northeast-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "CognitoUserPoolDomainParameter=\"upload-img-use-pool\""
image_repositories = []
